apiVersion: apps/v1
kind: Deployment
metadata:
  name: gamer-gambit-runner
  labels:
    app: gamer-gambit-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gamer-gambit-runner
  template:
    metadata:
      labels:
        app: gamer-gambit-runner
    spec:
      containers:
      - name: runner
        image: myoung34/github-runner:latest
        env:
        - name: REPO_URL
          value: "https://github.com/2mOlaf/gamer-gambit"
        - name: RUNNER_TOKEN
          value: "ACYMZHUT3LMPA5H7U7GTPRDITPTYM"
        - name: RUNNER_NAME
          value: "gamer-gambit-k8s-runner"
        - name: RUNNER_WORK_DIRECTORY
          value: "/tmp/runner/work"
        - name: RUNNER_GROUP
          value: "default"
        - name: LABELS
          value: "kubernetes,self-hosted,discord-bot"
        - name: DOCKER_HOST
          value: "tcp://localhost:2376"
        - name: DOCKER_TLS_VERIFY
          value: "1"
        - name: DOCKER_CERT_PATH
          value: "/certs/client"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        securityContext:
          privileged: true
        volumeMounts:
        - name: runner-temp
          mountPath: /tmp/runner
        - name: docker-certs
          mountPath: /certs
      - name: dind
        image: docker:dind
        env:
        - name: DOCKER_TLS_CERTDIR
          value: "/certs"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        securityContext:
          privileged: true
        volumeMounts:
        - name: docker-certs
          mountPath: /certs
        - name: docker-storage
          mountPath: /var/lib/docker
      volumes:
      - name: runner-temp
        emptyDir: {}
      - name: docker-certs
        emptyDir: {}
      - name: docker-storage
        emptyDir:
          sizeLimit: 10Gi
      restartPolicy: Always
