apiVersion: apps/v1
kind: Deployment
metadata:
  name: kallax
  namespace: gamer-gambit
  labels:
    app: kallax
    component: discord-bot
    version: v1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kallax
      component: discord-bot
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kallax
        component: discord-bot
        version: v1.0.0
    spec:
      containers:
      - name: kallax
        image: ghcr.io/2molaf/kallax-discord-bot:main
        imagePullPolicy: Always
        workingDir: /app
        env:
        - name: DISCORD_TOKEN
          valueFrom:
            secretKeyRef:
              key: DISCORD_TOKEN
              name: kallax-config
        - name: DISCORD_GUILD_ID
          valueFrom:
            secretKeyRef:
              key: DISCORD_GUILD_ID
              name: kallax-config
              optional: true
        - name: DATABASE_PATH
          valueFrom:
            secretKeyRef:
              key: DATABASE_PATH
              name: kallax-config
        - name: BGG_API_BASE_URL
          valueFrom:
            secretKeyRef:
              key: BGG_API_BASE_URL
              name: kallax-config
        - name: COMMAND_PREFIX
          valueFrom:
            secretKeyRef:
              key: COMMAND_PREFIX
              name: kallax-config
        - name: DEFAULT_WEEKLY_STATS_CHANNEL
          valueFrom:
            secretKeyRef:
              key: DEFAULT_WEEKLY_STATS_CHANNEL
              name: kallax-config
        - name: STEAM_API_KEY
          valueFrom:
            secretKeyRef:
              key: STEAM_API_KEY
              name: kallax-api-keys
              optional: true
        - name: XBOX_API_KEY
          valueFrom:
            secretKeyRef:
              key: XBOX_API_KEY
              name: kallax-api-keys
              optional: true
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - pidof python
          initialDelaySeconds: 90
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - pidof python && test -f /app/data/kallax.db
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 5
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: kallax-data
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
