apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kallax-data
  namespace: gamer-gambit
  labels:
    app: kallax
    component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # Uncomment and modify if you have a specific storage class
  # storageClassName: your-storage-class
