name: Kallax Test Build

on:
  push:
    branches: [ test ]
    paths: 
      - 'discord/kallax/**'
      - '.github/workflows/kallax-test.yml'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: kallax-discord-bot
  BOT_DIRECTORY: discord/kallax

jobs:
  test-build:
    runs-on: [self-hosted, kubernetes, discord-bot]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Test Python environment
      run: |
        echo "Python version:"
        python --version
        echo "Pip version:"
        python -m pip --version
        echo "Working directory:"
        pwd
        echo "Contents of bot directory:"
        ls ${{ env.BOT_DIRECTORY }}/

    - name: Install requirements
      working-directory: ${{ env.BOT_DIRECTORY }}
      run: |
        echo "Installing Python dependencies..."
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Test Python imports
      working-directory: ${{ env.BOT_DIRECTORY }}
      run: |
        echo "Testing Python imports..."
        python -c "
        import sys, os
        sys.path.append('.')
        try:
            from utils.database import Database
            from utils.bgg_api import BGGApiClient
            print('✅ Bot modules imported successfully')
        except ImportError as e:
            print(f'❌ Import error: {e}')
            sys.exit(1)
        "

    - name: Test Docker build
      run: |
        echo "Testing Docker build..."
        cd ${{ env.BOT_DIRECTORY }}
        docker build -t test-kallax .
        echo "Docker build successful!"

    - name: Test container registry login
      run: |
        echo "Testing container registry login..."
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin
        echo "Registry login successful!"

    - name: Summary
      run: |
        echo "✅ All test steps completed successfully!"
